name: Node.js CI



on:
 push:
   branches: [ "master" ]
 pull_request:
   branches: [ "master" ]



jobs:
 test:
   runs-on: ubuntu-latest
   strategy:
         matrix:
           node-version: [22.20.0,18.x]
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v4
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'



     - name: Install dependencies
       run: npm install



     - name: Run Jest tests
       run: npm test

